# SQLMonitor Configuration

# Provide password OR encryptedPassword,encryptionKey. See the documentation to find about password encryption.

# isolationLevel:Transaction isolation level to apply on the connection
#Supported values are TRANSACTION_READ_UNCOMMITTED, TRANSACTION_READ_COMMITTED, TRANSACTION_REPEATABLE_READ and TRANSACTION_SERIALIZABLE
#Default is TRANSACTION_READ_UNCOMMITTED

servers:
    - displayName: "Instance1"
      driver: "com.mysql.jdbc.Driver"
      connectionString: "jdbc:mysql://localhost:3388/test"
      user: "root"
      password:
      encryptedPassword: "IGVtC9eudmgG8RDjmRjGPQ=="
      isolationLevel: "TRANSACTION_READ_UNCOMMITTED"
      commands:
        - command: "select age from test1 where age = 29"
          displayPrefix: "Expedia"
        - command: "select age from test1 where age = 32"
          displayPrefix: "DerbySoft"

    - displayName: "Instance2"
      driver: "com.mysql.jdbc.Driver"
      connectionString: "jdbc:mysql://localhost:3388/database2"
      user: "root"
      password: "root"
      encryptedPassword:
      isolationLevel: "TRANSACTION_READ_UNCOMMITTED"
      commands:
        - command: "select value from monitortest where id = 1"
          displayPrefix: "Expedia"
        - command: "select value from monitortest where id = 2"
          displayPrefix: "DerbySoft"

numberOfThreads: 5
encryptionKey: "welcome"

#Runs the queries every taskDelaySeconds configured
taskSchedule:
    numberOfThreads: 1
    taskDelaySeconds: 60



# Make sure the metric prefix ends with a |
#This will create this metric in all the tiers, under this path.
#metricPrefix: "Custom Metrics|SQL|"
#This will create it in specific Tier. Replace <ComponentID> with TierID
metricPrefix: "Server|Component:<ComponentID>|Custom Metrics|SQL|"