# Configure the SQLMonitor
servers:
    - server: "localhost"
      driver: "com.mysql.jdbc.Driver"
      connectionString: "jdbc:mysql://localhost:3306/demo"
      user: "root"
      #Provide password or encryptedPassword and encryptionKey. See the documentation to find about password encryption.
      password:

      encryptedPassword: "IGVtC9eudmgG8RDjmRjGPQ=="
      encryptionKey: "welcome"


commands:
   - command: "select foo as foobar from bar where id = 10"
     displayPrefix: "Expedia"
   - command: "select foo as foobar from bar where id = 5"
     displayPrefix: "DerbySoft"

# Make sure the metric prefix ends with a |

metricPrefix: "Custom Metrics|SQL|"
