# Configure the SQLMonitor
servers:
    - server: "localhost"
      driver: "com.mysql.jdbc.Driver"
      connectionString: "jdbc:mysql://localhost:3388/test"
      user: "root"
      #Provide password or encryptedPassword and encryptionKey. See the documentation to find about password encryption.
      password: "root"

      encryptedPassword:
      encryptionKey:
      #Transaction isolation level to apply on the connection
      #Supported values are TRANSACTION_READ_UNCOMMITTED, TRANSACTION_READ_COMMITTED, TRANSACTION_REPEATABLE_READ and TRANSACTION_SERIALIZABLE
      #Default is TRANSACTION_READ_UNCOMMITTED
      isolationLevel: "TRANSACTION_READ_UNCOMMITTED"


commands:
   - command: "select value from monitortest where id = 1"
     displayPrefix: "Expedia"
   - command: "select value from monitortest where id = 2"
     displayPrefix: "DerbySoft"

# Make sure the metric prefix ends with a |

metricPrefix: "Custom Metrics|SQL|"