# Vertica Instance
host: "192.168.57.102"
port: 5433
database: "VMart"
user: "dbadmin"
password: "password"
metricPrefix:  "Custom Metrics|Vertica|"

#System tables for which stats has to be shown. Supported values are ACTIVE_EVENTS, DISK_STORAGE, HOST_RESOURCES, IO_USAGE,
# NODE_STATES, QUERY_METRICS, RESOURCE_USAGE, SYSTEM_RESOURCE_USAGE, SYSTEM. All other values will be ignored
sysTables: 
  - objectName: "ACTIVE_EVENTS"
    metrics:
      include:
        - event_code : "Event Code"
        - event_id : "Event ID"
        - event_posted_count : "Event Posted Count"

  - objectName: "DISK_STORAGE"
    metrics:
      include:
        - rank : "Rank"
        - throughput : "Throughput"
        - latency : "Latency"
        - disk_block_size_bytes : "Disk Block Size Bytes"
        - disk_space_used_blocks : "Disk Space Used Blocks"
        - disk_space_used_mb : "Disk Space Used MB"
        - disk_space_free_blocks : "Disk Space Free Blocks"
        - disk_space_free_mb : "Disk Space Free MB"
        - disk_space_free_percent : "Disk Space Free Percent"

  - objectName: "HOST_RESOURCES"
    metrics:
      include:
        - open_files_limit : "Open Files Limit"
        - threads_limit : "Threads Limit"
        - core_file_limit_max_size_bytes : "Core File Limit Max Size Bytes"
        - processor_count : "Processor Count"
        - processor_core_count : "Processor Core Count"
        - opened_file_count : "Opened File Count"
        - opened_socket_count : "Opened Socket Count"
        - opened_nonfile_nonsocket_count : "Opened NonFile NonSocket Count"
        - total_memory_bytes : "Total Memory Bytes"
        - total_memory_free_bytes : "Total Memory Free Bytes"
        - total_buffer_memory_bytes : "Total Buffer Memory Bytes"
        - total_memory_cache_bytes : "Total Memory Cache Bytes"
        - total_swap_memory_bytes : "Total Swap Memory Bytes"
        - total_swap_memory_free_bytes : "Total Swap Memory Free Bytes"
        - disk_space_free_mb : "Disk Space Free MB"
        - disk_space_used_mb : "Disk Space Used MB"
        - disk_space_total_mb : "Disk Space Total MB"

  - objectName: "IO_USAGE"
    metrics:
      include:
        - read_kbytes_per_sec : "Read KBytes Per Second"
        - written_kbytes_per_sec : "Written KBytes Per Second"

  - objectName: "NODE_STATES"
    metrics:
      include:
        -  node_state : "Node State"

  - objectName: "QUERY_METRICS"
    metrics:
      include:
        -  active_user_session_count : "Active User Session Count"
        -  active_system_session_count : "Active System Session Count"
        -  total_user_session_count : "Total User Session Count"
        -  total_system_session_count : "Total System Session Count"
        -  total_active_session_count : "Total Active Session Count"
        -  total_session_count : "Total Session Count"
        -  running_query_count : "Running Query Count"
        -  executed_query_count : "Executed Query Count"

  - objectName: "RESOURCE_USAGE"
    metrics:
      include:
        - request_count : "Request Count"
        - local_request_count : "Local Request Count"
        - active_thread_count : "Active Thread Count"
        - open_file_handle_count : "Open File Handle Count"
        - memory_requested_kb : "Memory Requested KBytes"
        - address_space_requested_kb : "Address Space Requested KBytes"
        - wos_used_bytes : "WOS Used Bytes"
        - wos_row_count : "WOS Row Bytes"
        - ros_used_bytes : "ROS Used Bytes"
        - ros_row_count : "ROS Row Count"
        - total_row_count : "Total Row Count"
        - total_used_bytes : "Total Used Bytes"

  - objectName: "SYSTEM_RESOURCE_USAGE"
    metrics:
      include:
        - average_memory_usage_percent : "Average Memory Usage Percent"
        - average_cpu_usage_percent : "Average CPU Usage Percent"
        - net_rx_kbytes_per_second : "Net RX KBytes Per Second"
        - net_tx_kbytes_per_second : "Net TX KBytes Per Second"
        - io_read_kbytes_per_second : "IO Read KBytes Per Second"
        - io_written_kbytes_per_second : "IO Written KBytes Per Second"

  - objectName: "SYSTEM"
    metrics:
      include:
        - designed_fault_tolerance : "Designed Fault Tolerance"
        - node_count : "Node Count"
        - node_down_count : "Node Down Count"
        - current_fault_tolerance : "Current Fault Tolerance"
